### ISSUE TITLE
Moving "Commit" tab to different position produces errors in the outout.

### ISSUE THREAD

**Issue by NineAlexT** [godotengine/godot-git-plugin#111]
Godot 3.5 beta5, Git Plugin v2.1.0.
If you move the "Commit" tab to a dock position other than it's default you get three identical errors in the output log every time you save a file:
`scene/gui/tab_container.cpp:855 - Condition "!child" is true.`
Moving the tab back to it's default position stops the errors.

**Comment by akien-mga** [comment]
Fixed by https://github.com/godotengine/godot/pull/61381.
