### ISSUE TITLE
Failure to initilaize on Linux/Godot 3.5 rc1 using plugin v2.1.0

### ISSUE THREAD

**Issue by solorvox** [godotengine/godot-git-plugin#112]
Steps:
1) Install from web (2.1.0) or via AssetLib
2) Project/Version Control/Setup Version Control
3) Click initialize, network options all left blank

Note: Project has existing git repo that was working with earlier version of godot 3.4 w/ git-plugin (1.2.x)

Installed path:
addons/godot-git-plugin/

Error in output:
 scene/gui/popup_menu.cpp:885 - Index p_idx = -1 is out of bounds (items.size() = 1).
 core/script_language.cpp:227 - Condition "!global_classes.has(p_class)" is true. Returned: String()
 Resource file not found: res://.
 VCS Plugin path is invalid
 No VCS plugin is initialized. Select a Version Control Plugin from Project menu.

Godot Engine v3.5.rc1.official
Plugin versions: 2.1.0
OS: Linux Mint 20.3

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/61249.

**Comment by ChronicallySerious** [comment]
@Calinou Thanks for attending to this! I am not sure if this one is related to that one however because the error is a non-crash and OP is using the correct combination of a Godot build and a plugin version. 

This one is a new issue

**Comment by ChronicallySerious** [comment]
@solorvox Would you be able to send a zip of a smaller project that demonstrates this behaviour for you?

**Comment by solorvox** [comment]
>  @ChronicallySerious 
Created a new project, unzipped the addons folder into it and tried to do VCS/setup/init and got error.  But here is the project anyway.
[git-test.zip](https://github.com/godotengine/godot-git-plugin/files/8832205/git-test.zip)

**Comment by ChronicallySerious** [comment]
Correction: It does appear that my changes in Godot to fix #111 have indeed fixed this issue in Godot 3.5rc2, and hence only Godot 3.5rc1 is showing this problem and yet Godot 3.5rc2 and Godot 3.5rc3 are not

**Comment by ChronicallySerious** [comment]
The problem doesn't reappear in Godot 3.5rc2+ but once you confirm on your side, I would be okay to close this issue

**Comment by solorvox** [comment]
> The problem doesn't reappear in Godot 3.5rc2+ but once you confirm on your side, I would be okay to close this issue

I can confirm that it works as expected in Godot 3.5 rc3.  Thanks
