### ISSUE TITLE
Initializing broken with v2 + 3.5rc6 (or I am too stupid)

### ISSUE THREAD

**Issue by Poolitzer** [godotengine/godot-git-plugin#116]
Hi.

I tried using this plugin. I installed it into the addons folder, and using it to initialize git seems to work, I get this window

![image](https://user-images.githubusercontent.com/25934244/177980570-3cf7ab57-02f3-4dbb-99cd-79d24b568fd8.png)

When I press on initialize, I get the version control + commit windows, but they are empty

![image](https://user-images.githubusercontent.com/25934244/177980654-1b1343f6-2783-4c7a-b1cd-2146863a9282.png)

Maybe I need to fill in password, but I dont know which password would be asked for there? I (want to) use git with ssh, but for now just having it local would also be enough.

**Comment by ChronicallySerious** [comment]
@Poolitzer Your last screenshot shows there's an error in the Output tab. Could you please share that if it's coming from the plugin?

Usually, once you are at the stage where you claim to be, the plugin should be working properly. You can try hitting the Wiki for an FAQ on how to set up the network features. Also, you need to click Apply after making changes in the Remote login settings.

**Comment by Poolitzer** [comment]
Good catch, it is
` No VCS plugin is initialized. Select a Version Control Plugin from Project menu.`
Happens after I press initialize.

Lets say I dont want network features for now, I emptied that windows

![image](https://user-images.githubusercontent.com/25934244/177991687-5006331d-238a-4f16-b454-8c325ad269ec.png)

The other one is as empty as before.

a git folder was setup + gitignore files, and git status reports untracked files as expected, I just thought they would show up in the UI, somewhere.

**Comment by ChronicallySerious** [comment]
Are there any other logs in the console window? You would have to run Godot from the terminal to see them if you are not already. 

I will try to reproduce this in the meantime. Can you tell us your Git plugin version and Linux flavour/distro?

**Comment by ChronicallySerious** [comment]
Also just to confirm, did you install this plugin from the asset library?

**Comment by Poolitzer** [comment]
Wow. I found the issue. I thought for sure that I downloaded v2 because I used the wiki and everything, because I knew which godot version I had. Turns out, I did download v1. I was too stupid.

Downloaded v2, replaced the files in the addon, works as expected. So sorry for causing this trouble.
