### ISSUE TITLE
Not working with Godot 3.5

### ISSUE THREAD

**Issue by inc0der** [godotengine/godot-git-plugin#117]
The addon does initialize when setting up version control and the menus do show up on the right sidebar **but it does not display and branches or commits**, it's all empty.

I don't get any errors in the version control tab, and I don't have any errors in the output or debugger tab either, and currently the console window is not opening for me so I'm unsure if it's reporting errors there.

I attached a screenshot where vscode displays the git changes and branch and Godot is not showing anything.

![image](https://user-images.githubusercontent.com/14813394/183255765-9afa9ca3-d165-4319-a31d-90fdea7a8d40.png)

**Comment by ChronicallySerious** [comment]
@inc0der Any chance you downloaded the plugin through Asset library? I am yet to release this there. Using v2.1.0 release with Godot 3.5 should work correctly

**Comment by ChronicallySerious** [comment]
We are waiting for this PR to get merged and deployed - https://github.com/godotengine/godot-asset-library/pull/260

After that, we will be able to submit 3.5 plugins to the asset library and it is expected that it will make the version of this plugin compatible with Godot 3.4 disappear when viewing the asset library through Godot 3.5

**Comment by inc0der** [comment]
I did download through the asset library, I will clone and copy from the master branch to see how that works out for me. Thanks for the information.

**Comment by inc0der** [comment]
All is working now, thanks for the help. 
![image](https://user-images.githubusercontent.com/14813394/183265589-242875a3-60a3-47ec-b38e-50ca98721872.png)
