### ISSUE TITLE
Build for macOS 10.12+ (Same as Godot)

### ISSUE THREAD

**Issue by daviewales** [godotengine/godot-git-plugin#119]
The pre-built binaries appear to be built for macOS 11+
However, Godot itself appears to support macOS 10.12+.

Would it be possible to tweak the GitHub actions to use the same magic that's used to target 10.12 in the Godot builds?

I can't quite figure out what the magic is, but I'm wondering if it's one of these:

https://github.com/godotengine/godot/blob/b3bd08207032ca146319f4b25654bcddd31ee401/platform/macos/detect.py#L117
https://github.com/godotengine/godot/blob/b3bd08207032ca146319f4b25654bcddd31ee401/misc/dist/macos_template.app/Contents/Info.plist#L39
https://github.com/godotengine/godot/blob/b3bd08207032ca146319f4b25654bcddd31ee401/misc/dist/macos_tools.app/Contents/Info.plist#L42

**Comment by ChronicallySerious** [comment]
The macOS binaries have been built using this Github workflow - https://github.com/godotengine/godot-git-plugin/blob/master/.github/workflows/build.yml

I wonder if I can just change the `macos-11` to `macos-10.15`, but it looks like they have been [deprecated by Github](https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/)

**Comment by ChronicallySerious** [comment]
Also, should probably try to get some attention to https://github.com/godotengine/godot-git-plugin/issues/59 while we are at it

**Comment by ChronicallySerious** [comment]
Changing macos-11 to macos10.15 didn't work - https://github.com/godotengine/godot-git-plugin/runs/7712698049?check_suite_focus=true

I also see that godot-cpp also uses `macos-11`, so a better way to find how it can be done is to look into how godot-cpp (3.5) is getting compiled.

**Comment by ChronicallySerious** [comment]
This will be available in the next v2.x release
