### ISSUE TITLE
Engine freezes completely when trying to push or pull.

### ISSUE THREAD

**Issue by leha-code** [godotengine/godot-git-plugin#124]
I have tried pushing and pulling and the engine froze completely and I had to kill it with Task Manager and re-start it.

**Comment by Calinou** [comment]
Which Godot version and OS are you using?

**Comment by ChronicallySerious** [comment]
If you start Godot from the terminal and then trigger a push or a pul, you should be able to see what's happening during the freeze. The plugin will show "Git-like" logs when performing these network features.

However, the push however is a blocking task in the editor, and so large pushes or pulls will stall the editor

**Comment by ChronicallySerious** [comment]
@leha-code Is that error from when you try to enable the plugin from the editor settings? Usually, you need to go into `Project -> Version Control` to enable this plugin.

**Comment by LennyPhoenix** [comment]
Can confirm, I am getting the same problem. Logs show the following:
```
GitAPI: Performing push to origin
```
That't it from all I can see :/

**Comment by ChronicallySerious** [comment]
It should eventually return back with some logs if you don't see any errors right away. Sometimes the SSH auth can take a long time to establish.

**Comment by LennyPhoenix** [comment]
I'm only trying to push a single LoC commit here, so I don't think it should take any longer than a second or two.

**Comment by ChronicallySerious** [comment]
If you leave it running, it will eventually return with some timeout errors or authentication errors. It will be really helpful to see those to fix this problem

**Comment by LennyPhoenix** [comment]
Alright, I'll leave it running for a bit. I've not got my Username or Password set as I'm using SSH and didn't think there would be any need to enter those in, are they still required in this situation?

**Comment by ChronicallySerious** [comment]
SSH credentials are only used when using a remote that's configured to hit an SSH-based remote repository. Same for HTTPS.

**Comment by LennyPhoenix** [comment]
```
ERROR: GitAPI: Could not connect to remote "origin". Are your credentials correct? Try using a PAT token (in case you are using Github) as your password. Error -1: failed to connect to github.com: Network is unreachable
   at: _push (godot-git-plugin/src/git_api.cpp:562)```

**Comment by LennyPhoenix** [comment]
I'm using SSH, do I still need to setup a personal access token?

**Comment by LennyPhoenix** [comment]
![image](https://user-images.githubusercontent.com/57148878/184370808-3a8c26c4-0e81-4b85-b4d0-47a3fafbe186.png)
This is what my settings look like, my SSH key doesn't have a password set, and the repository uses an SSH remote.

**Comment by ChronicallySerious** [comment]
Using SSH will not require you to create a PAT. The `Network is unreachable` error is interesting, I am not sure I have ever encountered that before.

@leha-code Yes, right now, the push and pulls are blocking tasks in the editor, which means some amount of editor-freeze will occur during network operations.

**Comment by ChronicallySerious** [comment]
The ability to make an empty commit is currently up for debate. I initially let users create empty commits for added flexibility. If you want to directly commit all the unstaged files OR directly commit all the staged files which using your mouse, then you can click on the text editor and press `Super+Enter`. 

If you do have some opinions around if an empty commit should be allowed, you may open an issue against the godot repo.

**Comment by ChronicallySerious** [comment]
I don't think we are a place to be able to asynchronously do network operations because once you add multithreading to fix a problem, you 2 more problems get. So this can be closed for now. 

However, I will try to repro @LennyPhoenix 's issue separately. It would be great if you could open an issue separately with more info around the `Network is unreachable` error.

**Comment by paddomanno** [comment]
For anyone coming across this (was the first page on DDG search results for me):
If you, like me, experience not just some freezing but it actually fails to pull or push and prints an error in the Output tab, 
see my answer [here](https://github.com/godotengine/godot-git-plugin/issues/299#issuecomment-5039382874)for a possible fix.
In short: I got it working by using a specific type of SSH key
