### ISSUE TITLE
Can't push with SSH

### ISSUE THREAD

**Issue by LennyPhoenix** [godotengine/godot-git-plugin#125]
Attempting to push using SSH leads to the following error in console after about a minute of unresponsiveness.

```
ERROR: GitAPI: Could not connect to remote "origin". Are your credentials correct? Try using a PAT token (in case you are using Github) as your password. Error -1: failed to connect to github.com: Network is unreachable
   at: _push (godot-git-plugin/src/git_api.cpp:562)
```

**Comment by LennyPhoenix** [comment]
Godot 3.5, Linux

Here is my VCS config:

![VCS Settings](https://user-images.githubusercontent.com/57148878/184370808-3a8c26c4-0e81-4b85-b4d0-47a3fafbe186.png)

**Comment by ChronicallySerious** [comment]
@LennyPhoenix Could you try to run `ssh -Tv git@github.com` on your CLI to test if your SSH access to Github is in good condition?

**Comment by LennyPhoenix** [comment]
Sure, but I haven't had any problems with Git in other projects so I'm not sure that would be the problem. I'll check in a minute once I get home just in case its something silly like that.

**Comment by LennyPhoenix** [comment]
```
Hi LennyPhoenix! You've successfully authenticated, but GitHub does not provide shell access.
debug1: channel 0: free: client-session, nchannels 1
Transferred: sent 2104, received 2344 bytes, in 0.2 seconds
Bytes per second: sent 8511.9, received 9482.9
debug1: Exit status 1
```

Looks fine to me, cloning a repository from the command line (this one to be exact) yields a normal result:

```
❯ git clone git@github.com:godotengine/godot-git-plugin.git
Cloning into 'godot-git-plugin'...
remote: Enumerating objects: 7890, done.
remote: Counting objects: 100% (814/814), done.
remote: Compressing objects: 100% (334/334), done.
remote: Total 7890 (delta 449), reused 766 (delta 419), pack-reused 7076
Receiving objects: 100% (7890/7890), 248.83 MiB | 4.04 MiB/s, done.
Resolving deltas: 100% (1402/1402), done.
```
Pushing and pulling from the command line also works as expected.

**Comment by markeel** [comment]
I am also getting this same error message when I click the "sync" button at the bottom of the "commit tab"

Could not connect to remote "origin". Are your credentials correct? Try using a PAT token (in case you are using Github) as your password. Error -16: Failed to retrieve list of SSH authentication methods: Failed getting response

I am not using Github but SSH to a local server.

I can do a git push just fine from the command line: I had manually done 
* git remote add origin git@<server>:<path>
* git push --set-upstream origin master

I was just trying to see how the plugin handled a push.

I am using 3.5 and 2.1.0 of the plugin

**Comment by fkeyzuwu** [comment]
I'm having the same error as @markeel . What's interesting is that when I generate the PAT token at first it works fine for me, but after a few pushes to my remote repository it gives me the same error, when nothing really changed. when I make a new PAT token, everything works again, but again after a few pushes it gives me the same error.

**Comment by curtking** [comment]
Same issue here trying to push to Bitbucket.  I've run `ssh -T git@bitbucket.org` and I get "authenticated via ssh key. You can use git to connect to Bitbucket. Shell access is disabled."  So I'm confident that my connection to Bitbucket is good.  I get the same message as @markeel when I try to push.

**Comment by markeel** [comment]
BTW I opened a new issue: #172 with a potential fix that may be related to this issue.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-git-plugin/issues/193, which is more detailed. As a workaround, use a RSA key instead of ED25519.
