### ISSUE TITLE
Unable to load addon ... Base type is not EditorPlugin.

### ISSUE THREAD

**Issue by davidjreese** [godotengine/godot-git-plugin#129]
Error when ENABLING the plugin via the godot projects add-ons interface. This error is presented in a dialog.

open Unable to load addon script from path: 'res://addons/godot-git-plugin/git_api.gdns' Base type is not EditorPlugin.

Using: v3.5.1.stable.official [6fed1ffa3]
OS: Mac
Validated Install: plugin is installed in the correct directory and i enabled the unsigned dlls

**Comment by ChronicallySerious** [comment]
This is a known issue which we plan to fix in the 4.0 compatible version of this plugin. For now, in 3.x, you should be able to enable the plugin from Project > Version Control.

**Comment by davidjreese** [comment]
ah, i had tried that but didn't think it worked b/c the new tab wasn't showing on the side panel (because the control split pane was too small). I just noticed the button appear to scroll the tabs. Thanks!
