### ISSUE TITLE
Plugin is blank on mac (godot 4.10)

### ISSUE THREAD

**Issue by Pixelatex** [godotengine/godot-git-plugin#143]
Tried the latest v3 build with the latest godot build but seems like the plugin is just blank.

![image](https://user-images.githubusercontent.com/12593377/209671297-fea39b8b-73ab-443a-a6bb-a5a7b77feb87.png)

There are no errors shown in the output though, unsure what I can do about this.

**Comment by twaritwaikar** [comment]
There should also be a Commit tab on the right.

You may need to scroll using the navigation  buttons beside the Node, Inspector, History tabs in Godot 4.0-beta10. 

The tab that you have opened is used only to display diffs and commits only when you click on the items in the Commit tab. 

You can see more info about these tabs in the Wiki. 

---

However this only applies when we confirm that your Commit tab is working properly 😅

**Comment by Pixelatex** [comment]
Ah, mae culpa. 

This one is on me. Everything seems to work fine!

**Comment by twaritwaikar** [comment]
I went through a few names for it, like 'Commit Diff' or 'Changes', etc., But I eventually landed on 'Version Control' for simplicity since that tab can later be used for something else.

How about 'Version Changes'?

**Comment by Pixelatex** [comment]
Just my two cents but the current "Commit" panel does a lot more than just commit and is more worthy of the "Version control" name. Is there a need for a second panel? Ideally, some form of a popup window would be nicer. (not sure if GD allows that)

Back to the question itself:
I guess for me it was unclear that I first had to click an active change to see something in there so you could perhaps add a placeholder there to indicate that the blankness is ok and what the user should do.

**Comment by jinyangcruise** [comment]
This issue saved me…… Never found there were a History and a Commit next to Node. Thx!
