### ISSUE TITLE
FYI: Reddit support thread & possible missing instruction step

### ISSUE THREAD

**Issue by follower** [godotengine/godot-git-plugin#15]
FYI there's currently a Reddit thread "[VCS integration in 3.2](https://old.reddit.com/r/godot/comments/ewx9ss/vcs_integration_in_32/)" where someone is having trouble getting started with this plugin. You may wish to provide assistance. :)

Also, in the replies someone mentions "Check if the library is enabled in the project settings" which seems to be a step missing from the existing installation instructions?

**Comment by IronicallySerious** [comment]
Thank you for informing me. The plugin should not require you to manually
enable it from the settings. However, I will provide assistance
nevertheless.

**Comment by IronicallySerious** [comment]
Kept on hold for closing in case adding the step to enable the plugin turns out to be essential later on.
