### ISSUE TITLE
Cannot show Chinese correctly

### ISSUE THREAD

**Issue by jinyangcruise** [godotengine/godot-git-plugin#150]
<img width="250" alt="image" src="https://user-images.githubusercontent.com/42859362/211192459-ee7e1629-52f9-4782-8848-73428a29d26c.png">
<img width="458" alt="image" src="https://user-images.githubusercontent.com/42859362/211201170-2b4f197e-58f4-433e-b135-80f615e0d08e.png">

**Comment by leejunxian98** [comment]
Same Issue here, using windows 11

**Comment by markeel** [comment]
This appears to be a problem with the encoding assumptions made when reading from the libgit2 library.  That library is simply an array of characters.  It could be encoded as anything, but probably is encoded as UTF-8.  What it is NOT encoded as a 32 bit unicode encoding, which is what godot::String holds internally.  The constructor used assumes that it is the char array is 8 bits which is then converted to a 32 bit internal storage (see String::copy_from() in core/string/ustring.cpp).

A reasonable fix is to assume all data from libgit2 is UTF8.  This should handle almost everyone,   For those that have to have their data stored in another encoding, there would need to be an "encoding" parameter probably at the VCS data level (at the same place the user/password/ssh key are recorded.  

I believe that an enhancement should be created for including an "encoding" parameter, and that the current plugin should be updated to assume UTF-8.

I'll create a pull request with the defaulting to UTF-8, but please discuss if this doesn't seem like a good solution.

**Comment by jinyangcruise** [comment]
I think default to UTF-8 willl be good. On the other hand, `For those that have to have their data stored in another encoding, there would need to be an "encoding" parameter probably at the VCS data level`, what if I have different encoding files, one encoding parameter is not enough for this situation. This remainds me of some software I used before like Ultra Edit, IntelliJ IDEA and so on, they can show charactors well. I guess they can detect file's encoding or do something to transfer different encoding data to one common encoding maybe? But detecting encoding may be complicated.

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot-git-plugin/issues/218#issuecomment-1924466413 for a possible solution.

**Comment by markeel** [comment]
I closed the out of date pull request and created a new one
