### ISSUE TITLE
Commit tab does not appear in v4.0.beta11

### ISSUE THREAD

**Issue by seanbrar** [godotengine/godot-git-plugin#151]
Version Control tab appears in the bottom console, and History on the right side, but the commit tab is not added/initialized.

I'm using the official Linux 64bit executable.

On startup, the console displays:
```
Found a repository at /home/user/.local/share/godot-projects/project-name/.git/.
Selected repository path: /home/user/.local/share/godot-projects/project-name/.git/.
```

**Comment by nelsonayamashita** [comment]
Had this problem earlier too. I've found that the current workaround is to just resize the right dock so that it fits the commit tab.

**Comment by seanbrar** [comment]
I think my issue may have been different. Testing against the 3.5 version of Godot and the plugin with everything the same (window size, monitor, etc.) showed the correct behavior.

That said, after coming back to Godot today, everything suddenly works as expected. I didn't do anything as far as I know, and I can't replicate the issue right now by simply removing/re-adding the plugin.

Since the issue no longer exists for me, I'll be closing this issue.
