### ISSUE TITLE
The tab disappear when click on deleted files

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot-git-plugin#152]
As stated in title when I click on a deleted file the right tab disappear:
before:
![image](https://user-images.githubusercontent.com/13235119/212259108-661ebf53-a0aa-43a6-a5a6-2cba7ca33352.png)

after when I click in `properylist`:
![image](https://user-images.githubusercontent.com/13235119/212258855-38383d12-7f2f-4e6b-bf04-a54508c462aa.png)

**Comment by git2013vb** [comment]
Also  I suggest a warning pop-up each time we click in discharge changes "x" to avoid accidental double click on listed file.

**Comment by markeel** [comment]
I looked at this to see if I could reproduce this. 

When I clicked on a deleted file the "Version Control" window was updated appropriately.

This is on the current godot editor 4.0.2.

Can you reproduce this issue?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.
