### ISSUE TITLE
MacOS refuses to let plugin run

### ISSUE THREAD

**Issue by SkidaDev** [godotengine/godot-git-plugin#153]
When you try to use the plugin on macos, it won't load because it has an "unidentified developer"
I tried to bypass this by right clicking the file and pressing open, and allowing it to open. Then I tried to open it in godot, same message. Please help ._.

**Comment by ajreckof** [comment]
Have you tried this : 

https://support.apple.com/fr-fr/guide/mac-help/mh40616/mac

**Comment by twaritwaikar** [comment]
I assume what you tried was this step [here](https://github.com/godotengine/godot-git-plugin/issues/58#issuecomment-793451881) that is also mentioned in the Wiki. Do you mean to say that this solution has stopped working on your Mac?

**Comment by bruvzg** [comment]
If right-clicking doesn't work, you can unlock it using `xattr -dr com.apple.quarantine /path/to/plugin` command, or ad-hoc sign in locally (if Xcode is installed) `codesign -s - --force --deep  /path/to/plugin`.

**Comment by BoydWiglaf** [comment]
I have tried the above suggestions but am still getting an Error.  "Unable to load addon script from path: 'res://addons/godot-git-plugin/git_api.gdns' Base type is not EditorPlugin."  I downloaded the addon/plugin from https://godotengine.org/asset-library/asset/1410
I am using Godot Engine v3.5.stable.official [991bb6ac7]

**Comment by twaritwaikar** [comment]
Any chance you are trying to enable this plugin through the Project Settings? We have a different way of initializing this plugin mentioned here - https://github.com/godotengine/godot-git-plugin/wiki

**Comment by BoydWiglaf** [comment]
Yes I was.  Thanks.  I have it working now.

**Comment by markeel** [comment]
I think this should be closed, since it was an attempt to enable this plugin in the project settings.
If anything there should be an issue to "allow" a VCS plugin to be enabled, or quit making a VCS plugin a special case.  That seems to be a request against the main godot engine however.

**Comment by Calinou** [comment]
Closing per @markeel's comment.
