### ISSUE TITLE
nullptr VCS extension instance error on beta14

### ISSUE THREAD

**Issue by seanbrar** [godotengine/godot-git-plugin#155]
The plugin does not initialize properly when opening my project with beta14.

Output shows the following error:
```
Cannot get class 'GitPlugin'.
Received a nullptr VCS extension instance during construction.
```

The same project does not experience this issue in beta13.

**Comment by RobertoMaurizzi** [comment]
Compiled master at 0a9e6e478e after a week of not using my computer at all and right now my projects that had godot-git-plugin enabled crash the editor after they're loaded. I didn't have time to investigate yet...
Quick fix: delete the addons/godot-git-plugin directory for now.

**Comment by seanbrar** [comment]
I can confirm that opening projects with this plugin with beta17 closes/crashes the editor. Removing the plugin allows the project to open normally.

I've stuck with beta13 since opening this issue, but until there is a fix, I will just do without.

Keeping this issue open since the different behavior (plugin not working vs. editor crashing) could be caused by the same error/incompatibility.

**Comment by twaritwaikar** [comment]
The demo project with plugin version v3.0.0-beta2 seems to be loading correctly in Godot 4.0-rc4
