### ISSUE TITLE
(Feature request) Reset functionality

### ISSUE THREAD

**Issue by ColinGilbert** [godotengine/godot-git-plugin#158]
We cannot revert changes that the user doesn't want, such as an accidental file deletion. Could we have such a feature?

**Comment by twaritwaikar** [comment]
The `X` button used to discard file changes should be of help here. E.g. if you delete a file then it would appear as deleted in the `Commit` tab. For there you can revert your delete i.e. bring the file back.
![image](https://user-images.githubusercontent.com/31801364/221407774-23a5db96-9073-42e2-8c02-248787c8d1e7.png)
