### ISSUE TITLE
No VCS plugin installed error on beta 16.

### ISSUE THREAD

**Issue by Frontrider** [godotengine/godot-git-plugin#159]
On Godot 4 beta 16, I get this error when I try to click project->version control->version control settings.

![image](https://user-images.githubusercontent.com/6755034/215767243-b36975a5-0c22-4461-a6d1-31d564c9d8ee.png)

**Comment by twaritwaikar** [comment]
The new version v3.0.0-beta2 seems to load correctly in Godot 4.0-rc6
