### ISSUE TITLE
Godot RC-5 and plugin 3.0.0-beta2 reporting "No VCS plugin is initialized"

### ISSUE THREAD

**Issue by RobertoMaurizzi** [godotengine/godot-git-plugin#163]
I tested the new version of the plugin with RC-5 and a new project, downloading the plugin from the Asset window.
Godot detects the plugin and offers the menus to select Git as VCS and the other menu to open the dialog to set user, password, ssh key files and passphrases (in glorious non-HDPI supporting resolution).
However when I click "Apply" all I get is:
`No VCS plugin is initialized. Select a Version Control Plugin from Project menu.`

**Comment by GodoterFR** [comment]
I had the same error until I understood that I had to check the "Connect to VCS" box.
I don"t know if it's same for you.

<a href="https://imgbb.com/"><img src="https://i.ibb.co/pP0k1Kg/vcs-fleche.png" alt="vcs-fleche" border="0"></a>

**Comment by RobertoMaurizzi** [comment]
O____O

I literally didn't see it, between my eyesight and a 4K 15 inches monitor 😅😅😅
Thanks @GodoterFR, it works, closing! :brownbag:

**Comment by mbrealm** [comment]
Thank you for documenting this issue @RobertoMaurizzi .

I had the same problem - I didn't see that toggle, and I overlooked it completely in the Setup instructions. Drove me nuts for a short time until I hit upon this thread.
