### ISSUE TITLE
not working in godot 4.0.2 rc1

### ISSUE THREAD

**Issue by TomerconDevelopers** [godotengine/godot-git-plugin#177]
![image](https://user-images.githubusercontent.com/62302722/229278139-f2bf5b76-0245-4e32-85ff-db6a24a4c29f.png)

**Comment by TomerconDevelopers** [comment]
![image](https://user-images.githubusercontent.com/62302722/229296192-65eb260b-1bac-4b40-8153-011f8a9c288a.png)

**Comment by CanTheAlmighty** [comment]
The file `godot-git-plugin.gd ` literally does not exist on the current release even though the config mentions it.

**Comment by clemens-tolboom** [comment]
In #183 I made is work by creating the file https://github.com/godotengine/godot-git-plugin/issues/183#issuecomment-1532709104

In that issue the UI reports file not found error.

Are these duplicates: #183 / #185 / #176 ?

**Comment by Calinou** [comment]
- Duplicate of https://github.com/godotengine/godot-git-plugin/issues/183.
