### ISSUE TITLE
Auto-initialize?

### ISSUE THREAD

**Issue by gamedevsam** [godotengine/godot-git-plugin#18]
It seems every time I start up the godot editor and open my project I have to re-initialize the VCS functionality. Is there no way to enable it automatically once the plugin is saved in the project's GDNative plugins section?

**Comment by IronicallySerious** [comment]
This sort of a functionality should be provided by the engine, if any. The Git plugin cannot expect yo initialize itself. I recommend opening a similar issue at godotengine/godot or godotengine/godot-proposals

**Comment by Calinou** [comment]
I'll close this per @IronicallySerious' comment, as this is not an issue with the plugin itself.
