### ISSUE TITLE
Made too many changes in a commit, project now crashes every time I load it (Godot 4.0)

### ISSUE THREAD

**Issue by Syogren** [godotengine/godot-git-plugin#201]
For context, I moved a bunch of textures into folders and made some spheres in a circle.  Then I tried to stage the changes...and it crashed.  Now every time I open the project, it crashes.

EDIT: Using the terminal to stage commit the changes worked.  I think the Godot IDE just got confused?

**Comment by daveTheOldCoder** [comment]
The may be a duplicate of https://github.com/godotengine/godot-git-plugin/issues/188

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-git-plugin/issues/188.
