### ISSUE TITLE
perhaps this is not the right place but please update the official git extension for 4.1.1.stable.mono

### ISSUE THREAD

**Issue by RakibRyan** [godotengine/godot-git-plugin#207]
### Godot version

4.1.1.stable.mono

### System information

Windows 11 Enterprise Version	22H2 Installed  OS build	22621.2283 Experience	Windows Feature Experience Pack 1000.22662.1000.0

### Issue description

outdated git plugin. How can I praise godot and recommend to others when the basic functionality is broken.

### Steps to reproduce

.

### Minimal reproduction project

.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-git-plugin/issues/196.

> How can I praise godot and recommend to others when the basic functionality is broken.

I have to remind you that we have a [Code of Conduct](https://godotengine.org/code-of-conduct). Please stay constructive.
