### ISSUE TITLE
Doesn't work on Godot 4.1.2

### ISSUE THREAD

**Issue by BigDC** [godotengine/godot-git-plugin#209]
I am on Windows 10, 64.   I use Godot 4.1.2 and I still get the same errors as described in here >>>  [Update plugin for Godot 4.1 due to GDExtension compatibility breakage
](https://github.com/godotengine/godot-git-plugin/issues/196)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-git-plugin/issues/196#issuecomment-1728694273. Please don't open additional duplicate issues, as this won't help the issue be resolved faster.
