### ISSUE TITLE
Unable to load addon script from path.. 4.2 stable

### ISSUE THREAD

**Issue by larinius** [godotengine/godot-git-plugin#210]
Same error since 2022. This add-on never worked for me in Godot 4.

![image](https://github.com/godotengine/godot-git-plugin/assets/5310985/81081d3e-6c33-4d11-9dae-815cb5eac54d)

**Comment by BenjaTK** [comment]
![imagen](https://github.com/godotengine/godot-git-plugin/assets/73806216/067e0456-67e4-4404-ba59-3f243233439d)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-git-plugin/issues/196.
