### ISSUE TITLE
Addon is not recognized / installed properly on Godot 4.2 stable

### ISSUE THREAD

**Issue by madeirander** [godotengine/godot-git-plugin#212]
After installing the addon from the asset store, it is just not recognized or working properly:

![image](https://github.com/godotengine/godot-git-plugin/assets/6282555/c822fd7d-0fa8-46b0-a369-29c9788d0e99)

![image](https://github.com/godotengine/godot-git-plugin/assets/6282555/a1b88808-44b5-4608-9c3c-e9a0c682543b)

Am I missing something?

**Comment by madeirander** [comment]
The doc clearly says that we should not manually enable it, so I just expected it to work out of the box after installing, but after going to `Project -> Version Control -> Version Control Settings`, I get this message:

![image](https://github.com/godotengine/godot-git-plugin/assets/6282555/6727aff2-3a64-49fe-935c-9c64d251bab9)

**Comment by madeirander** [comment]
These are the messages I get when opening with the console:

```
Godot Engine v4.2.stable.official.46dc27791 - https://godotengine.org
OpenGL API 3.3.0 NVIDIA 545.84 - Compatibility - Using Device: NVIDIA - NVIDIA GeForce GTX 960

...

ERROR: GDExtension configuration file must contain a "configuration/compatibility_minimum" key: res://addons/godot-git-n
   at: load_gdextension_resource (core/extension/gdextension.cpp:884)
ERROR: Failed loading resource: res://addons/godot-git-plugin/git_plugin.gdextension. Make sure resources have been imp.
   at: (core/io/resource_loader.cpp:274)
ERROR: Error loading extension: res://addons/godot-git-plugin/git_plugin.gdextension
   at: (core/extension/gdextension_manager.cpp:234)
Godot Engine v4.2.stable.official.46dc27791 - https://godotengine.org
Vulkan API 1.3.260 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 960

ERROR: GDExtension configuration file must contain a "configuration/compatibility_minimum" key: res://addons/godot-git-n
   at: load_gdextension_resource (core/extension/gdextension.cpp:884)
ERROR: Failed loading resource: res://addons/godot-git-plugin/git_plugin.gdextension. Make sure resources have been imp.
   at: (core/io/resource_loader.cpp:274)
```

I downloaded it from the AssetLib, but for some reason the `git_plugin.gdextension` file is not the same that shows [here](https://github.com/godotengine/godot-git-plugin/blob/2f160a2b7926efb728025ab07a29858ff71981a1/demo/addons/godot-git-plugin/git_plugin.gdextension#L4). Mine doesn't have that line, so I added it, but still It doesnt work, I got these errors:

```
ERROR: No GDExtension library found for current OS and architecture (windows.x86_64) in configuration file: res://addonn
   at: load_gdextension_resource (core/extension/gdextension.cpp:911)
ERROR: Failed loading resource: res://addons/godot-git-plugin/git_plugin.gdextension. Make sure resources have been imp.
   at: (core/io/resource_loader.cpp:274)
ERROR: Error loading extension: res://addons/godot-git-plugin/git_plugin.gdextension
   at: (core/extension/gdextension_manager.cpp:234)
```

The binaries are not in the folder as the engine excepts. Anybody knows where I can get these or how to build them?

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-git-plugin/issues/196.
