### ISSUE TITLE
No GDExtension library found for linux.x86_64

### ISSUE THREAD

**Issue by Catan365** [godotengine/godot-git-plugin#213]
I installed plugin in Godot 4.2.1 Flathub and gets this errors:

> core/extension/gdextension.cpp:911 - No GDExtension library found for current OS and architecture (linux.x86_64) in configuration file: res://addons/godot-git-plugin/git_plugin.gdextension
> Failed loading resource: res://addons/godot-git-plugin/git_plugin.gdextension. Make sure resources have been imported by opening the project in the editor at least once.

Also i added "compatibility_minimum = 4.1.0" to git_plugin.gdextension .

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-git-plugin/issues/196.
