### ISSUE TITLE
Attempt to get non-existent interface function: script_instance_create. on godot 4.2.1

### ISSUE THREAD

**Issue by licamla** [godotengine/godot-git-plugin#217]
load error on godot 4.2.1
```
Attempt to get non-existent interface function: script_instance_create.
  Unable to load GDExtension interface function script_instance_create()
  core/extension/gdextension.cpp:748 - GDExtension initialization function 'git_plugin_init' returned an error.
  Failed loading resource: res://addons/godot-git-plugin/git_plugin.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
  Attempt to get non-existen
```

In order to use this plugin,  need to build godot 4.2.1  with enable support for deprecated features?

**Comment by Calinou** [comment]
Which version of the plugin are you using? Are you using a custom build of the editor (specifically, one with double-precision physics)?

> In order to use this plugin, need to build godot 4.2.1 with enable support for deprecated features?

Support for deprecated features is already enabled by default.

**Comment by licamla** [comment]
> Which version of the plugin are you using? Are you using a custom build of the editor (specifically, one with double-precision physics)?
> 
> > In order to use this plugin, need to build godot 4.2.1 with enable support for deprecated features?
> 
> Support for deprecated features is already enabled by default in Godot builds. There is a `DISABLE_DEPRECATED` define in the engine but it's rarely ever used.

thanks for your message.
the version of the plugin is v3.1.0. the editor is a custom build without deprecated features. I use gentoo linux, the installation script is disable deprecated features by default.

this plugin is working after rebuild godot with enable support for deprecated features.
