### ISSUE TITLE
Incorrect display of Russian characters

### ISSUE THREAD

**Issue by Purpursarkans** [godotengine/godot-git-plugin#218]
![изображение](https://github.com/godotengine/godot-git-plugin/assets/26607874/c6932e69-b422-439f-9820-7aaff81c37d6)

OS: archlinux
OS lang: ru
godot installed from steam

**Comment by bruvzg** [comment]
Nothing in the plugin seems to be Unicode aware.

https://github.com/godotengine/godot-git-plugin/blob/2f160a2b7926efb728025ab07a29858ff71981a1/godot-git-plugin/src/git_plugin.cpp#L385

Probably should be `godot::String msg = godot::String::utf8(git_commit_message(commit.get()));`

https://github.com/godotengine/godot-git-plugin/blob/2f160a2b7926efb728025ab07a29858ff71981a1/godot-git-plugin/src/git_plugin.cpp#L278

Same here for branch names and probably every single other use of `godot::String`.

**Comment by Purpursarkans** [comment]
the previous comment has already suggested why this is so, but I want to add 1 more place without Russian characters, because of which it is impossible to index and commit changes
![изображение](https://github.com/godotengine/godot-git-plugin/assets/26607874/527d9c47-809b-47d6-b654-1c020e0351f0)

**Comment by Calinou** [comment]
Would https://github.com/godotengine/godot-git-plugin/pull/190 help with this?

**Comment by bruvzg** [comment]
> Would https://github.com/godotengine/godot-git-plugin/pull/190 help with this?

It seems to be fixing at least some of the strings, not sure if it's all.

**Comment by Purpursarkans** [comment]
change 
> https://github.com/godotengine/godot-git-plugin/blob/259ae989f48486b9c9f6fedbe09af3da99fc3a31/godot-git-plugin/src/git_plugin.cpp#L385

on

`godot::String msg = godot::String::utf8(git_commit_message(commit.get()));`

it really helped to fix the Russian language in the commit list, but the Russian language still needs fixing in the index and in the version control tab
![изображение](https://github.com/godotengine/godot-git-plugin/assets/26607874/55fc4ff5-6b1f-4896-a34b-dc938d9c0c2e)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-git-plugin/issues/150.
