### ISSUE TITLE
Ubuntu 18.04lts Godot 3.2.1 Plugin Fail

### ISSUE THREAD

**Issue by Alderin1974** [godotengine/godot-git-plugin#22]
Greetings,
I'm getting these errors when I follow the installation steps. It is similar to issue #11 but not exact. Please let me know if you need more details.

```
 Can't open dynamic library: /home/alderin/Dropbox/Code/Godot/AldVenture/bin/x11/libgitapi.so. Error: /home/alderin/Dropbox/Code/Godot/AldVenture/bin/x11/libgitapi.so: undefined symbol: deflateInit_
 modules/gdnative/gdnative.cpp:483 - No valid library handle, can't get symbol from GDNative object
 modules/gdnative/nativescript/nativescript.cpp:1506 - No nativescript_init in "res://bin/x11/libgitapi.so" found
```

**Comment by IronicallySerious** [comment]
I think this is coming from the same reason as the issue you linked above. Zlib is the dependency which is not build found while loading the plugin, however, this is not the case for all Ubuntu systems, which is why this is getting difficult to track. 

I will keep this issue open because the error is quite different.

**Comment by Alderin1974** [comment]
Digging into zlib, I'm finding a ton of things I've installed come with their own zlib.so or similar. Each kernel seems to have a version, then python and ruby have their own versions, pkgconfig has its own version. It might be easiest to just include a version of zlib for the plugin.
I also downloaded and built libgit2 locally, but it didn't provide the .so referenced.

**Comment by IronicallySerious** [comment]
Did you mean to say that Libgit2 didn't build with its own Zlib version?

**Comment by Alderin1974** [comment]
> Did you mean to say that Libgit2 didn't build with its own Zlib version?

No, the libgitapi.so that the plugin has. I thought that if I could compile that on my system and drop it in that might solve the issue, but I didn't find a simple way to do that.

**Comment by IronicallySerious** [comment]
You may want to try again now. I pushed simpler build instructions on
master. The process also builds ligbit2 so it may help you.

**Comment by IronicallySerious** [comment]
Found the issue. Libgit2 has been compiled without the bundled Zlib, which means that it relies on the system to provide a libzlib.so in linux and likewise on other platforms.
Fixing this is merely recompiling libgit2 and flipping the switch: `USE_BUNDLED_ZLIB`

**Comment by IronicallySerious** [comment]
I recommend trying with the newer release v1.2: https://github.com/godotengine/godot-git-plugin/releases/tag/v1.2
Feel free to comment here if any issues occur.

**Comment by IronicallySerious** [comment]
Similar issues have now been fixed. This should also be fixed with the latest release. Closing until further reports come in.

**Comment by Alderin1974** [comment]
Sorry for the delayed response, but as a confirmation: Yes, it is fixed now. Thanks!
