### ISSUE TITLE
Could not display unicode commit message?

### ISSUE THREAD

**Issue by Muyangmin** [godotengine/godot-git-plugin#226]
I'm new for Godot and this plugin. For a testing purpose I downloaded example project and add this plugin into res:/ folder. The plugin works but I meet a problem after tried to perform the first commit: The history is displayed as garbled characters. (See the examples below)

Is there some settings I missed? Or the plugin is currently not support unicode chars?

**Environment: Windows 10, Language: Simplified Chinese.**
**Godot version: v4.2.1.stable.official [b09f793f5]**
**VCS plugin version: 3.1.0**

Raw commit message:  "添加 git 插件。" (just means, "Add git plugin.")
![image](https://github.com/godotengine/godot-git-plugin/assets/8530661/072b3e64-9689-4c3f-a7ef-76cc922b7826)

Displayed in history and vcs window:
![image](https://github.com/godotengine/godot-git-plugin/assets/8530661/1cedb6eb-22ae-42a8-99ca-8c1ca7764124)

Thanks for reading and appreciate for any reply : )

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-git-plugin/issues/150.
