### ISSUE TITLE
Failed to push. Error -1: invalid refspec

### ISSUE THREAD

**Issue by PincoPallino-lang** [godotengine/godot-git-plugin#227]
"ERROR: GitPlugin: Failed to push. Error -1: invalid refspec refs/heads/ in godot-git-plugin\src\git_plugin.cpp:GitPlugin::_push#L542"
Using PAT and https.
No spaces in paths. (I don't know if it can help)
OS: Windows 11.
Godot version: 4.2.1.stable.official [b09f793f5]
OS language: Italian.
Godot language: English.
Plugin version: 3.1.0
First time pushing.

**Comment by PincoPallino-lang** [comment]
Turned out to be a dumb directory tree issue (unzipped uncorrectly). Closing.

**Comment by DenisBrenner** [comment]
I have the same issue, but I unzipped correctly. Is there anything else to solve this issue?
