### ISSUE TITLE
The Chinese characters displayed as garbled text after committing (Chinese garbled text issue).

### ISSUE THREAD

**Issue by WangYongxun** [godotengine/godot-git-plugin#228]
The Chinese characters displayed as garbled text only in the commit list. Chinese characters can be displayed correctly in Git Bash (with text encoding set to UTF-8). Is it possible to set the text encoding in the commit list to UTF-8 as well?
![Uploading 1.png…]()

```[tasklist]
### Tasks
- [ ] https://github.com/godotengine/godot-git-plugin/issues/150
```

**Comment by markeel** [comment]
I have a pull request #190 that I believe fixes this issue, but it has been stalled and hasn't had a reviewer look at it.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-git-plugin/issues/150.
