### ISSUE TITLE
Godot crush on initialization

### ISSUE THREAD

**Issue by spikestheraccon** [godotengine/godot-git-plugin#24]
I tried to activate plugin in my old project, but after initialization Godot crashes.
I noticed that the plugin created the folder .git in my project folder. But after reinitialization godot crashes with this error
![2020-04-08 23_37_49-Godot Engine - Sumochkin Forgotten Hero - Level_01_Lost_in_Nightmare_Sumochkin t](https://user-images.githubusercontent.com/56189267/78821392-dc1a9e80-79f2-11ea-8f6c-e2cf537e67ed.png)

Godot 3.2 - stable, windows 10

**Comment by IronicallySerious** [comment]
Could you see if `git config user.name` and `git config user.email` print anything when running on cmd?

**Comment by IronicallySerious** [comment]
I recommend trying with the newer release v1.2: https://github.com/godotengine/godot-git-plugin/releases/tag/v1.2
Feel free to comment here if any issues occur.

**Comment by spikestheraccon** [comment]
@IronicallySerious  it works now, thanks!

**Comment by IronicallySerious** [comment]
Thanks you checking out this plugin
