### ISSUE TITLE
Instructions for making a PAT

### ISSUE THREAD

**Issue by dragonforge-dev** [godotengine/godot-git-plugin#247]
I found the creation of a PAT a little time-consuming research-wise, so I thought I'd provide step-by-step instructions for you to add to the installation document.

1. Click your profile photo, and select **Settings** (near the bottom).
2. In the left sidebar click **<> Developer Settings**. (It’s the last option.)
3. On the next page, in the left sidebar, click **Personal access tokens**.
4. Click **Fine-grained token**.
5. Click **Generate new token**.
6. **Name** it something..
7. Set the **Expiration** for as long as you like. (We don’t recommend over 90 days).
8. Make a note to yourself in the **Description** field. (We suggest, “Using the Godot GitHub plugin.”)
9. Under **Repository access**, select **Only select repositories**.
10. Click the **Select Repositories** dropdown button that just appeared, and select your repo(s). (You can add as many as you like.)
11. Under **Permissions** open up **Repository permissions**. Scroll down to **Contents** and select **Read and Write** from the dropdown.
12. Scroll to the bottom and click the **Generate token** button.
13. Copy your token and store it somewhere. (**You will need it every time you restart Godot.**) _You cannot come back to Git to see what it is later, and will have to make a new one if you lose this one._

**Comment by dragonforge-dev** [comment]
P.S. I didn't see a way to do a PR with the wiki. If I missed it, please let me know.

**Comment by Calinou** [comment]
> P.S. I didn't see a way to do a PR with the wiki. If I missed it, please let me know.

I allowed edits from all users on this repository's wiki, so feel free to use the Edit button there 🙂

**Comment by dragonforge-dev** [comment]
Updated in the wiki, thanks!
