### ISSUE TITLE
Godot crashes on GitAPI initialization when the system console is toggled off

### ISSUE THREAD

**Issue by Serenitor** [godotengine/godot-git-plugin#25]
1. Start Godot 3.2.1
2. Hit Editor > Toggle System Console if not done so already
3. Try to initialize GitAPI
4. Godot crashes

Edit: Hm, now I can't reconstruct it anymore. Now Godot ALWAYS crashes when trying to initialize GitAPI. Sadly nothing is printed to the console.

**Comment by IronicallySerious** [comment]
What OS are you using perhaps?

**Comment by Serenitor** [comment]
Win10.
So the connection I initially made with the console window being toggled off or not seems to have been coincidental. Sadly this seems to happen "randomly" and I currently can't provide any proper reproduction steps. If I can't come up with anything better I'll just close this again. :/

**Comment by IronicallySerious** [comment]
That is still a valid issue. I'd rather you keep it open while I investigate why it might happen.

**Comment by UrakAttack** [comment]
GitAPI initialization also causes Godot to crash for me as well, on both Godot 3.2 and 3.2.1 (Windows 10 64 bit), with zero console output.

**Comment by IronicallySerious** [comment]
@Serenitor @UrakAttack Could you see if `git config user.name` and `git config user.email` print anything in cmd?

**Comment by Serenitor** [comment]
> @Serenitor @UrakAttack Could you see if `git config user.name` and `git config user.email` print anything in cmd?

yes, this is set up properly for me, other git clients work, too.

**Comment by IronicallySerious** [comment]
I recommend trying with the newer release v1.2: https://github.com/godotengine/godot-git-plugin/releases/tag/v1.2
Feel free to comment here if any issues occur.

**Comment by Serenitor** [comment]
looks good, have not been able to crash Godot with the new release :)

**Comment by IronicallySerious** [comment]
Sounds good. Thank you for trying out this plugin!
