### ISSUE TITLE
Can I ship compiled plugin in my project and keep it MIT.

### ISSUE THREAD

**Issue by DioKiriie** [godotengine/godot-git-plugin#251]
So my project uses MIT license. I have seen that compiled version of plugin in releases comes with License and Thirdparty licenses. Can I still ship my project under MIT license if I include your plugin in it? IF not then I gues I should just left and guide of how to install this plugin.

**Comment by Calinou** [comment]
> Can I still ship my project under MIT license if I include your plugin in it?

Yes, MIT allows redistribution (modified or unmodified).
