### ISSUE TITLE
Los plugins no funcionan

### ISSUE THREAD

**Issue by Tyler8556** [godotengine/godot-git-plugin#255]
Al importar un plugin a Godot 4 y intentar activarlo, aparece:

Unable to load addon script from path: 'res://addons/zylann.scatter/tools/plugin.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/zylann.scatter/plugin.cfg' to prevent further errors.

#198 
#11

**Comment by Calinou** [comment]
The error messages references Zylann's scatter plugin, not the Godot Git plugin.
