### ISSUE TITLE
Remove unnecessary line from build_libs.sh

### ISSUE THREAD

**Issue by Janglee123** [godotengine/godot-git-plugin#28]
I seem this line is unnecessary in build_libs.sh

https://github.com/godotengine/godot-git-plugin/blob/5ced3f6eaf3200389c931eb029f11a5d58187c0e/build_libs.sh#L14

I think the build script should not need to install a package. But the main reason for it is that `apt-get` is not used by every Linux distribution. Installing a package also requires root privileges. So users have to run the script with sudo then it might compile binary which only accessible by the root.
Instead, we can use `scons -v` to check the availability of scons.

**Comment by IronicallySerious** [comment]
Valid point. Not all will use SCons. We can remove the line entirely and
let the user install it.

**Comment by Calinou** [comment]
Feel free to open a PR to do it :slightly_smiling_face:

**Comment by Janglee123** [comment]
Removed in #21.
