### ISSUE TITLE
Plugin detected but not working

### ISSUE THREAD

**Issue by Nutriz** [godotengine/godot-git-plugin#30]
Hi,

I have followed the wiki for the installation:

I have the "godot-git-plugin-v1.2-x11" folder inside my root project folder:
![Capture d’écran du 2020-04-21 23-59-04](https://user-images.githubusercontent.com/7358899/79918208-3cb2ce00-842c-11ea-84b1-95257d6cb27b.png)

The GDNative plugin is detected inside godot:
![Capture d’écran du 2020-04-22 00-01-11](https://user-images.githubusercontent.com/7358899/79918300-6835b880-842c-11ea-9bef-ff7ac3ea046a.png)

But when I go to Project -> Version Control -> Set up version control, I have this: 
![Capture d’écran du 2020-04-22 00-01-51](https://user-images.githubusercontent.com/7358899/79918339-7be11f00-842c-11ea-90f5-8f7a92832387.png)

I'm on Linux (Ubuntu Budgie 19.10). I have tried to switch Godot to english but same error. I have also tried with a project already versioned with git, but still the same popup.

**Comment by IronicallySerious** [comment]
The plugin zip contents should be present along side the project.godot file
of your project. This means the bin/ folder, git_api.gdns and
git_api.gdnlib should be present in the same directory as the project.godot
file.

A very recent change was made to the wiki that made this clear once again.

I recommend just extracting the contents once again but to the correct
directory in your case. This means you should be able to see the bin/
folder in the plugin binaries present along side your project.godot file.
This should get rid of the issue and make godot recognise the plugin.

**Comment by Nutriz** [comment]
Ho my bad, when I extracted the zip, my OS created a folder. It's working fine now :)
