### ISSUE TITLE
Why not install to the addons directory

### ISSUE THREAD

**Issue by Megaguy32** [godotengine/godot-git-plugin#39]
As the Godot documentation suggests, https://docs.godotengine.org/en/stable/tutorials/plugins/editor/installing_plugins.html, Plugins go into res://addons/plugin_name.
but the installation instructions instruct we put the contents alongside the project.godot file and won't work otherwise.

Why doesn't this project follow the convention?
Imo, the root project folder would get cluttered if plugins were to reside there, and its not good for project hierarchy organization.

**Comment by IronicallySerious** [comment]
Quite frankly I wasn't aware this was the way to install plugins when I worked on the initial iterations of this plugin. The documentation page you have mentioned has been added in March 2020, and we released the plugin in 2019.

I think this would be a much better way to work if people could just install their plugins. Thanks for reporting, I will check it out.

**Comment by syntopicus** [comment]
I was able to get it working from `res://addons/godot-git-plugin/` by editing `git_api.gdns` and `git_api.gdnlib`.

e.g. 
```
# edit git_api.gdns
[ext_resource path="res://addons/godot-git-plugin/git_api.gdnlib" type="GDNativeLibrary" id=1]
```
```
# edit git_api.gdnlib
OSX.64="res://addons/godot-git-plugin/bin/osx/release/libgitapi.dylib"
Windows.64="res://addons/godot-git-plugin/bin/win64/release/libgitapi.dll"
X11.64="res://addons/godot-git-plugin/bin/x11/release/libgitapi.so"
```
