### ISSUE TITLE
Suggestion to update wiki

### ISSUE THREAD

**Issue by 3koozy** [godotengine/godot-git-plugin#46]
Dear **gents** ,
thank you for you good work on this plugin and I hope you accept my humble suggestion:

I think it will help many beginners and (NOOBs :D) to add : 
"**Installing git from www.git-scm.com to your computer and configure user name and email**"
as one of the prerequisites to install this plugin , as it may seems obovious (just now for me ^^") 
I think it will make the wiki beginner-friendly and who won't want that ? 😄 

Regards , **Aziz**.

**Comment by 3koozy** [comment]
by the way , I can confirm this plugin v1.2 works with no problems on godot v3.2.2(stable) on windows 10.

**Comment by IronicallySerious** [comment]
Thanks, I have now added this to the wiki :)

https://github.com/godotengine/godot-git-plugin/wiki
