### ISSUE TITLE
Button to select/unselect all

### ISSUE THREAD

**Issue by Deozaan** [godotengine/godot-git-plugin#50]
I like to keep my commits small and focused to just one specific feature I'm working on, if I can. It makes it easier to revert specific things without undoing a bunch of work that I want to keep.

But sometimes I forget to commit after finishing one task and start working on another thing and then another, etc. So when I finally take a break to commit, I have to selectively choose only the files that belong to the specific feature I want to commit.

Right now it's really a really annoying process! I have to manually unselect 50 files, stage and commit 3 files, then manually unselect 47 files, stage and commit 1 file, manually unselect 46 files, stage and commit 5 files, etc.

We really need a button to that will toggle between all files selected and unselected in the list. I imagine this button would fit nicely at the top of the list somewhere. Perhaps right next to the Refresh button.

Either that, or default everything in the list to unselected upon refreshing. After all, if you want to commit everything, there's already a handy "Stage All" button right there in the UI.

**Comment by Janglee123** [comment]
The commit dock is embedded into the editor and not depended on the plugin. The plugin only provides underneath functionality that version control system requires. Although the new [commit dock](https://github.com/godotengine/godot/pull/39255) has stage/unstage all button which is what you might be asking.

**Comment by Deozaan** [comment]
> the new commit dock has stage/unstage all button which is what you might be asking.

No. I don't think that is what I'm asking.

### The Problem

This is what things look like now:

![Godot DVCS](https://user-images.githubusercontent.com/227734/100761051-ac6c3c80-33af-11eb-866d-5a2eb84fd9dc.png)

That screenshot shows only 14 items selected, but note the size of the scrollbar. There are roughly 100 items in the list and they're all selected by default. What should I do if I want to commit only two of those files?

Here's how things work currently:

You must stage one or more files before you can commit them. The only way to stage a file is to use one of the two buttons under the list, "Stage Selected" and "Stage All," which effectively do the same thing because every file is selected by default.

That is the crux of my problem. And that problem leads to the following problem(s):

If the user wants to commit just a few files, they must take the time to manually unselect (nearly) every file, which there is no quick way to accomplish. You can't shift-select a bunch of them and unselect the checkboxes. You can use the arrow keys and spacebar to go through them all and unselect them, but even that is hindered by some weird UI issue where you have to press the arrow key twice to go to the next item after pressing the spacebar, which makes it faster just to click them. Clicking them is still a relatively slow process and adds a new problem of having to deal with click accuracy. In either case, they must each be toggled. One... by... one... by... one... by...

### Proposed Solutions

I would either like:

1. Behavior to be changed so that no files are selected by default.
2. A button that toggles all checkboxes to easily unselect all files in a single action.

That said, it looks like the new commit dock requires you to manually select each file to be staged and doesn't pre-select any files to be staged for you. This sounds a lot like option 1 above to me. 👍

**Comment by Calinou** [comment]
Since the commit dock is part of the editor itself, this feature request should be opened as a proposal on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository.

**Comment by IronicallySerious** [comment]
I think others have explained everything. Your proposal is really solvable in the Godot repo and not here so this proposal is better put in the godot-proposals repo as Calinou said. When this feature request reaches the proposal repo, we can close this one :)

You can find the instructions to open a proper proposal on godot-proposal [here](https://github.com/godotengine/godot-proposals#rules-for-submitting-a-proposal)

**Comment by Deozaan** [comment]
Thanks to all who explained things to me.

I've just opened a request on [the Godot proposals repository here](https://github.com/godotengine/godot-proposals/issues/1918).
