### ISSUE TITLE
Git plugin blocks Windows export from Linux

### ISSUE THREAD

**Issue by sarrowsmith** [godotengine/godot-git-plugin#51]
**Godot version:**

3.2.3, 3.2.3 mono

**Plugin version:**
1.2-x11

**OS/device including version:**

Ubuntu 20.04

**Issue description:**

Attempts to export to Windows result in "export template appears to be missing" error. Exports to Linux/X11, HTML5 and Max OSX all succeed. Problem only happens when the Git plugin has been added to the project.

**Steps to reproduce:**
In a project with the git plugin installed and "Windows Desktop" configured in export_presets.cfg:
`godot --export "Windows Desktop" demo.exe`
```...
ERROR: copy: Failed to open res://bin/win64/release/libgitapi.dll
   At: core/os/dir_access.cpp:298.
ERROR: _fs_changed: Project export failed for preset 'Windows Desktop', the export template appears to be missing.
   At: editor/editor_node.cpp:753.
```

**Minimal reproduction project:**

Unable to: git plugin causes project to exceed 10MB limit.

Also reported against godot as https://github.com/godotengine/godot/issues/44213

**Comment by Calinou** [comment]
This is a bug with Godot's GDNative handling on export, not the Git plugin.
