### ISSUE TITLE
Plugin Installation

### ISSUE THREAD

**Issue by MikeSundaysProgrammer** [godotengine/godot-git-plugin#55]
In the installation wiki there is an instruction that says to download the latest release. When I go to that link it shows 5 assets of the latest release. Which should I download?

**Comment by Janglee123** [comment]
Download corresponding file for your OS. If you are using windows download `godot-git-plugin-v1.2.1-windows.zip`. Last two are source code for a release, you probably don't need them.

**Comment by MikeSundaysProgrammer** [comment]
Ok thanks, but when i do that and unzip it inside my godot project it doesnt recognize any version control addons...

**Comment by IronicallySerious** [comment]
You should check if the location where you extract the plugin, as said in
point number 3 in
https://github.com/godotengine/godot-git-plugin/wiki#installation, is
correct.

If you extract the zip, with software like WinRAR, it will create a folder
of the same name and extract inside it, which you don't want. The .gdnlib
and the .gdns files and the bin/ folder need to be in the same directory as
your project.godot file.

**Comment by MikeSundaysProgrammer** [comment]
After following your instructions it finally worked so a thousand thanks! Sorry for my misunderstanding while reading point number 3, but maybe it should be better to add more detail to the installation instructions(it may be a bit more text for the majority of users but for some, it may help clarify important info)?  Finally, was really surprised by the awesome and fast support you gave for a relative small repo!

**Comment by IronicallySerious** [comment]
Good to hear you got it working. I think the explanation in the wiki lacks this bit of very specific info and that is due to my intention to keep the wiki as simple as possible so the plugin is easy to pick up and use. 

What I will do instead is link this issue in the wiki so that other people who get this problem can come here :)

**Comment by MikeSundaysProgrammer** [comment]
Glad you are going to link this issur in thr wiki to help newcomers.

**Comment by ppweditor** [comment]
I am having the same problem with Godot not recognizing the plug-in.  I get an error message that No VCS addons are available.  This despite the fact that I have confirmed the location of the files as per above.  The bin folder, git_api.gdnlib, and git_api.gdns are all in my project file, along with the project.godot file.  And it still thinks there is no VCS plug-in available. Additionally, the GDNative tab in Project Settings recognizes git_api.gdnlib and that it is enabled. I've downloaded and confirmed installation of the VC+ Runtime 2019 and rebooted the computer. I can't think of anything else to try.  BTW, I'm using Godot 3.3.  Could that be the problem?  TIA for any help

**Comment by ChronicallySerious** [comment]
@ppweditor It should work with 3.3. Could you please provide the following details?

1. Project file structure (just to confirm)
2. Contents of the git_api.gd* files
3. Plugin version
4. Any errors that appear on the output panel related to this plugin.

**Comment by ppweditor** [comment]
Thanks for responding so promptly.  Attached are screen caps of the file system, output panel, etc.  The error on the output panel is clearly the most significant clue, but I can't make heads or tails out of what it's telling me.  The files seem to be where they are supposed to be. The plugin version is godot-git-plugin-v1.2.1-windows. Git version is Git-2.31.1-64-bit.

![2021-05-04 17_50_44-Window](https://user-images.githubusercontent.com/3966173/117075142-57d44100-ad02-11eb-9efe-9c4f918a28f9.png)
![2021-05-04 17_52_03-Window](https://user-images.githubusercontent.com/3966173/117075580-11331680-ad03-11eb-973f-f61242a25d0e.png)
![2021-05-04 17_54_05-Window](https://user-images.githubusercontent.com/3966173/117075183-691d4d80-ad02-11eb-856d-ca99d37ecf25.png)
![2021-05-04 17_54_58-Window](https://user-images.githubusercontent.com/3966173/117075195-6de20180-ad02-11eb-8ab4-6b4e9f9f5710.png)
Thanks for any help you can give me!

**Comment by ChronicallySerious** [comment]
@ppweditor That is very weird. I will look into this once I find some time. For now could you open a new issue with these details, since your issue is clearly not a "files in wrong directories" problem?

**Comment by carr91** [comment]
Did this ever get a solution?

**Comment by ChronicallySerious** [comment]
@carr91 I believe this should help most people facing this error https://github.com/godotengine/godot-git-plugin/issues/55#issuecomment-753456707

If it doesn't, please go ahead and create a new issue with your Godot details for it so that it is easier for us to investigate because in that case the problem would be much deeper than just putting the binaries in the wrong folder.

**Comment by KRV1** [comment]
> Did this ever get a solution?

There is an error in 1.2.1 relase zip. file for windows.
.gdnlib and .gdns files are missed, so use 1.2 release instead

**Comment by ChronicallySerious** [comment]
@KRV1 It doesn't look like these files are missing in v1.2.1, just saw the v1.2.1 release zip again. Could you check it again from [the release zip](https://github.com/godotengine/godot-git-plugin/releases/tag/v1.2.1)?

**Comment by KRV1** [comment]
I was probably wrong. A couple of days ago, when I downloaded the file and unzipped it, the two files were not deployed. 
Probably because of a failure in downloading.
