### ISSUE TITLE
Builds for linux/x11 have unstripped libgitapi.so

### ISSUE THREAD

**Issue by lnjX** [godotengine/godot-git-plugin#56]
The x11 builds are currently huge (in comparison to the other builds). Stripping the .so makes it *much* smaller (around 4 MB instead of 70).

**Comment by Janglee123** [comment]
Its a known issue that scons is not stripping debug symbols for release mode. Meanwhile, you can use `strip` command to remove debug symbols from the .so file.

**Comment by Calinou** [comment]
`strip` should be run on the next official release before uploading itL

**Comment by IronicallySerious** [comment]
Sure, also need to check why the symbols are added even in release mode before uploading future builds

**Comment by lnjX** [comment]
Off-topic: The open-source world is small: Hello @Calinou from Minetest xD

**Comment by ChronicallySerious** [comment]
Should be fixed with v1.2.2
