### ISSUE TITLE
Issue implementing VCS on Mac with godot-git-plugin-v1.2.1-osx

### ISSUE THREAD

**Issue by fenixn0909** [godotengine/godot-git-plugin#58]
<img width="197" alt="Report" src="https://user-images.githubusercontent.com/5415440/110233743-12dd9980-7f61-11eb-9799-8da4c1c33d08.png">

Mac OS version: 10.15.7 Catalina
Godot version: v3.2.4.rc3 
git version 2.24.3 (Apple Git-128)
godot-git-plugin-v1.2.1-osx

Extracted the zip then put the contents in same directory with project.godot, and it still says "No VCS addons are available." when pressed "Set Up Version Control" from project tab.

Note: I duplicated -libgitapi.dylib- file from ~bin/osx/release directory to project.godot directory, but still no luck.

Dose anyone get VCS done on mac successfully?

**Comment by ChronicallySerious** [comment]
Could you show us the contents of your `git_gdns.lib` file? Not that it's meant to be changed but paths could be wrong there

**Comment by fenixn0909** [comment]
Here you go:

<img width="621" alt="report2" src="https://user-images.githubusercontent.com/5415440/110257895-dd759200-7fda-11eb-90d9-a2d45d3504c4.png">

**Comment by bruvzg** [comment]
Godot RC3 is signed and notarized without `com.apple.security.cs.disable-library-validation` entitlement, and won't be able to load any library not signed by the same signature as the app.

With entitlement added https://github.com/godotengine/godot-build-scripts/pull/27 it will be able to load any library.

But all Gatekeeper restriction applies. If plugin is not signed and notarized framework, you'll need to open containing folder in Finder, right-click on binary, select `Open` from the menu and `Open` in the Gatekeeper dialog (do it twice, since `Open` won't be available in the dialog for the first time).

![Screenshot 2021-03-09 at 08 08 20](https://user-images.githubusercontent.com/7645683/110428006-4cbdb580-80b1-11eb-9486-02988f3f7e63.png)

**Comment by bruvzg** [comment]
Also, it's better to pack plugin into `framework`, since standalone `.dylib` can't be notarized.

```
.
└── libgitapi.framework
    ├── Resources -> Versions/Current/Resources
    ├── Versions
    │   ├── A
    │   │   ├── Resources
    │   │   │   └── Info.plist
    │   │   └── libgitapi
    │   └── Current -> A
    └── libgitapi -> ./Versions/Current/libgitapi
```

Where `./Versions/A/libgitapi` is the same `dylib`, and `Info.plist` is something like:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleExecutable</key>
	<string>libgitapi</string>
	<key>CFBundleGetInfoString</key>
	<string>Git Plugin for Godot</string>
	<key>CFBundleIdentifier</key>
	<string>org.godotengine.gitapi</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundlePackageType</key>
	<string>FMWK</string>
	<key>CFBundleShortVersionString</key>
	<string>1.2.1</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>1.2.1</string>
</dict>
</plist>
```

And `gdnlib` is changed accordingly:
```
OSX.64="res://bin/osx/release/libgitapi.framework/libgitapi"
```

**Comment by benetherington** [comment]
> Godot RC3 is signed and notarized without `com.apple.security.cs.disable-library-validation` entitlement, and won't be able to load any library not signed by the same signature as the app.
> 
> With entitlement added [godotengine/godot-build-scripts#27](https://github.com/godotengine/godot-build-scripts/pull/27) it will be able to load any library.
> 
> But all Gatekeeper restriction applies. If plugin is not signed and notarized framework, you'll need to open containing folder in Finder, right-click on binary, select `Open` from the menu and `Open` in the Gatekeeper dialog (do it twice, since `Open` won't be available in the dialog for the first time).
> 
> ![Screenshot 2021-03-09 at 08 08 20](https://user-images.githubusercontent.com/7645683/110428006-4cbdb580-80b1-11eb-9486-02988f3f7e63.png)

There's a [new process](https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unknown-developer-mh40616/mac) for trusting unknown developers. Not sure when they added it, but it's required in Sequoia at latest.

Try to run the binary, and you'll get an unknown developer popup. Trying to open the binary a second time will not add an "open anyway" button to the popup. Instead, you have to go to System Settings > Privacy and Security. Scroll down to the security section, and the name of the binary will be listed. Click the Open button.

**Comment by wrybit** [comment]
Is there any way to fix this? 
Cannot use it due to the company's restrictive Mac configuration rules - to secure the mac.

**Comment by Dragonatorul** [comment]
> Is there any way to fix this? Cannot use it due to the company's restrictive Mac configuration rules - to secure the mac.

The only way to "fix" this is to sign the executable with a certificate issued by Apple. That process is very tedious and costs. Not really feasible for open source projects in general. 

On newer MacOS versions (I'm on Tahoe 26.2) you'll need to open settings -> Privacy & Security and scroll down to the Security section. It will show up there after it fails to open and you'll have to click on "Open anyway".

<img width="835" height="836" alt="Image" src="https://github.com/user-attachments/assets/03e4b2a4-22c8-4144-af39-f22b7ce31b0b" />
