### ISSUE TITLE
Plug-in not recognized

### ISSUE THREAD

**Issue by ppweditor** [godotengine/godot-git-plugin#67]
I installed the plug-in, per the instructions, and verified that all files are in their proper location (see attached), but I'm still getting an error message that No VCS addons are available. 

![2021-05-04 17_50_44-Window](https://user-images.githubusercontent.com/3966173/117216022-19f01f00-adcd-11eb-8a25-a3b02e977bb1.png)
![2021-05-04 17_52_03-Window](https://user-images.githubusercontent.com/3966173/117216041-24aab400-adcd-11eb-9d31-bef26c46111e.png)

And I'm receiving the following error messages:

![2021-05-04 17_54_05-Window](https://user-images.githubusercontent.com/3966173/117216088-3ab87480-adcd-11eb-93e5-43aa1ea4b65d.png)
![2021-05-05 18_08_50-Godot_v3 3](https://user-images.githubusercontent.com/3966173/117216109-4310af80-adcd-11eb-9788-a48a91f332c2.png)

All the files it says it can't find are present in the project folder or the ../bin/win64/release folder inside the project folder.

![2021-05-05 18_16_51](https://user-images.githubusercontent.com/3966173/117216777-43f61100-adce-11eb-9eb2-d7b1d4f83e2d.png)
![2021-05-05 18_14_01-Godot Engine](https://user-images.githubusercontent.com/3966173/117216786-48222e80-adce-11eb-8a88-75a3340063c1.png)

If you need any more information, let me know.  Thanks.

**Comment by JPUlisses** [comment]
I have a friend having the same issue, however on my computer I do not have this issue. All my paths do not have strange characters. (Spaces and "-"). I say this because I suspect that is the only way how the file could not be found.

**Comment by ppweditor** [comment]
> I have a friend having the same issue, however on my computer I do not have this issue. All my paths do not have strange characters. (Spaces and "-"). I say this because I suspect that is one way how the file could not be found.

An interesting theory, but I tested it out by moving the entire project into a path with no spaces or other strange characters, and the problem persists. 

![2021-05-14](https://user-images.githubusercontent.com/3966173/118332085-865ad480-b4d7-11eb-849f-ed740c65d8df.png)

![2021-05-14-1](https://user-images.githubusercontent.com/3966173/118332103-8d81e280-b4d7-11eb-826a-2f1daab66d26.png)

![2021-05-14-2](https://user-images.githubusercontent.com/3966173/118332328-e9e50200-b4d7-11eb-9e09-ce4e5a109979.png)

**Comment by ChronicallySerious** [comment]
@ppweditor Just checking in case, was the issue solved?

**Comment by ppweditor** [comment]
Not in the sense that I got your plug-in to work. But I did get github working with my project folder. In light of that, I don't have a desperate need to have github integration in Godot. BTW, I'm just a hobbyist programmer and new to Github. I closed the issue because I figured there's no need to waste your time if I'm the only one reporting this problem.

**Comment by ChronicallySerious** [comment]
I understand. We'd rather keep it open just so we can track the problem and the solutions people tried. If you want, you can unsubscribe from this if you don't want to receive email alerts :)

**Comment by ChronicallySerious** [comment]
The Godot 3.5 beta1 is now live. And along with it, we released a v2.0.0 of this plugin which should fix this issue.
