### ISSUE TITLE
Add support for Apple Silicon architecture

### ISSUE THREAD

**Issue by Mercanuis** [godotengine/godot-git-plugin#68]
Found an issue similar to the "Plug-Ins Not Found" issue with my new M1 MacBook

Providing the screen shot below

![Screen Shot 2021-05-09 at 12 06 06 (2)](https://user-images.githubusercontent.com/35368863/117559358-874acb00-b0bf-11eb-9fea-952aa099b894.png)

**Comment by ChronicallySerious** [comment]
M1 support is not present in the plugin as of now. We will probably do it in the near future because Godot Editor has M1 support as well.

**Comment by ChronicallySerious** [comment]
Reference: #60

**Comment by Mercanuis** [comment]
Thanks for the update, will wait

**Comment by Sivli-Embir** [comment]
Bumping as its been a little over 4 months. Are there any formal plans to support this?

**Comment by ChronicallySerious** [comment]
Support for Apple Silicon was completed with #60 🎉

**Comment by ChronicallySerious** [comment]
The next releases shall have Apple Silicon builds once we enable creating releases from CI artifacts
