### ISSUE TITLE
Improvement: keep plugin open after restart

### ISSUE THREAD

**Issue by avnerh1** [godotengine/godot-git-plugin#71]
Suggestion: once git plugin is open, auto-open it every time godot editor starts, until the user intentionally disables it.
This will save repetitive actions for the user every time a restart/crash happens - exactly what scripts are good at.

**Comment by ChronicallySerious** [comment]
Thanks for the idea. We have actually received this before and since this problem is only solvable in the Godot Editor, the feature request was shifted to the official Godot repo here: https://github.com/godotengine/godot/issues/49309
