### ISSUE TITLE
Godot-Git where are the files going

### ISSUE THREAD

**Issue by gyrcom** [godotengine/godot-git-plugin#72]
I wish to use the git implementation on my main server for my godot projects. Where are the files being stored now? Where do I change the configuration to use my own local server?

**Comment by Calinou** [comment]
This plugin doesn't support pushing to remote repositories yet – you have to do that using the Git command line or another Git GUI client.

**Comment by ChronicallySerious** [comment]
The Godot 3.5 beta1 is now live. And along with it, we released a v2.0.0 of this plugin which introduces push/pull/fetch features and more. To use your own Git remote host, you just need to use the corresponding HTTPS or SSH endpoint that points to your Git remote host.
