### ISSUE TITLE
Unable to load Version 1.2.2

### ISSUE THREAD

**Issue by DPMakerQB** [godotengine/godot-git-plugin#81]
I put the addon in the project /addons folder, try to enable it and get this error:

Unable to load addon script from path: 'res://addons/godot-git-plugin/git_api.gdns' Base type is not EditorPlugin.

**Comment by DPMakerQB** [comment]
Guess you don't need to enable it. It just works. My bad.

**Comment by PixsaOJ** [comment]
How do you mean?

```
Unable to load addon script from path: 'res://addons/godot-git-plugin/git_api.gdns'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/godot-git-plugin/plugin.cfg' to prevent further errors.
```

This is what it says, and when I try to set up it says no VCS plugins detected.

Here is a screenshot of my project DIR:

![image](https://user-images.githubusercontent.com/12684017/138535593-d2ec950f-12f5-46b4-b72b-17d3a6df368c.png)

**Comment by PixsaOJ** [comment]
Update: Here is what's wrong:

```
PROJECT_DIR/addons/godot-git-plugin/x11/release/libgitapi.so: undefined symbol: pcre_free
 modules/gdnative/gdnative.cpp:502 - No valid library handle, can't get symbol from GDNative object
 modules/gdnative/nativescript/nativescript.cpp:1482 - No nativescript_init in "res://addons/godot-git-plugin/x11/release/libgitapi.so" found
```
