### ISSUE TITLE
what folders/files are needed to run this plugin?

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot-git-plugin#89]
I am installing from godot's built in plugin manager.
What things are needed to run this?

**Comment by ChronicallySerious** [comment]
@Shadowblitz16 Yes this was my first time submitting stuff to the Asset Library so apologies for not getting it right the first time. However, I am planning to make a new release to fix the Linux build issues like #82 and it shall also make it easier to install (likely remove the manual copying step altogether)

**Comment by rkunal** [comment]
Hi
I understand that the installation instructions/wiki should seem pretty obvious to the plugin developers.
But, coming from godot docs, as a first plugin to be installed, wiki is confusing and and so is jumping around issues. 
Now, I think, I have to install libpcre3. May be...... But brew search only shows "libre" . May be not.

**Comment by ChronicallySerious** [comment]
The Godot 3.5 beta1 is now live. And along with it, we released a v2.0.0 of this plugin which changes how this plugin behaves. Please open an issue if you detect any problems with it or the wiki still seems to be not completely obvious.
