### ISSUE TITLE
v1.0 not using Release of MSVC 14.x runtime, uses Debug

### ISSUE THREAD

**Issue by StarWolf3000** [godotengine/godot-git-plugin#9]
Adding Git support to my new project, the plugin complains about a missing VCRUNTIME140_1D.dll. This specific one is NOT part of the MS Visual C redistributable setup, only the non-debug (aka release) versions of the runtime libraries are installed with the setup (and I don't want to install Visual Studio 2019 just to get the Debug runtimes).

Somehow you forgot to switch the plugin into `Release` status for the v1.0 release.

**Comment by IronicallySerious** [comment]
Fix coming on this. I have made separate build process for Windows. Will port that to Linux soon and automate it with either TravisCI or Github Actions

**Comment by IronicallySerious** [comment]
@StarWolf3000 Does this issue seem to be solved with this release? https://github.com/godotengine/godot-git-plugin/releases/tag/v1.1

**Comment by StarWolf3000** [comment]
It does. Thanks!

**Comment by RichardO512** [comment]
i have the same problem with him but in 3.5.1, and really dont why the plugins not working even though in my friend laptop he can use it. btw my laptop are 2014 or 2015 and friend laptop are around 2018

**Comment by ChronicallySerious** [comment]
@RichardO512 Do you see any specific errors in the output console when you load this plugin?

**Comment by RichardO512** [comment]
@ChronicallySerious  it's okay now, I install this:
https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170
So if anyone have the same problem just click the above link and install both x86 and x64 your problem will fix.
