### ISSUE TITLE
Has git pull / push?

### ISSUE THREAD

**Issue by Sun-FreePort** [godotengine/godot-git-plugin#96]
I read some issue abot git pull / push feature, but can't see them in project.

We are support it?

**Comment by ChronicallySerious** [comment]
The new push/pull/fetch features (amongst other updates) are merged in the master branch and it will be usable, starting with Godot 3.5 beta 1. 

I will be creating a new release version with the new changes and upload it in Asset library so that Godot 3.5 beta 1 testers can use the new features.
