### ISSUE TITLE
Plugin (v2) not saving password in 3.5b1

### ISSUE THREAD

**Issue by Huckler** [godotengine/godot-git-plugin#98]
Every time I load up my project in 3.5b1, I have to re-enter my password under Project -> Version Control -> Set Up Version Control. It saves all settings EXCEPT for my password. I do have SSH keys as well. All credentials and SSH keys have been verified functional outside of Godot. I've also tried using a PAT.

Everything works fine until I exit the editor and re-load.

**Comment by ChronicallySerious** [comment]
The editor is intentionally not saving any passwords so as to not risk leaking the user's password to unintended audiences. It's to avoid having to deal with a security issue. 

However I am open to any alternatives to handling passwords.

**Comment by Huckler** [comment]
Fair enough - so we need to re-enter our password every time we open the editor? Or am I misunderstanding something. Thanks!

**Comment by ChronicallySerious** [comment]
Unfortunately, that's the workflow right now, yes. You may just use an SSH key without a passphrase (not recommended from a security standpoint). 

We are looking for a way to be able to save the password for the next subsequent startups.

**Comment by Huckler** [comment]
Got it - so, I do actually have that. I have an SSH key without a passphrase, and it continually fails. That same key works in other apps. I'll keep troubleshooting, but is there anything special I need to know about using my SSH key with Godot?

Thanks!

**Comment by ChronicallySerious** [comment]
@Huckler To make Godot use the SSH key to authenticate, you should make sure that the remote URL is an SSH endpoint and not a HTTPS one

**Comment by Huckler** [comment]
Yup, already verified that. That also doesn't work - I keep getting:

"GitAPI: Performing push to origin godot-git-plugin\src\git_api.cpp:576 - GitAPI: Could not connect to remote "origin". Are your credentials correct? Try using a PAT token (in case you are using Github) as your password. Error -16: Failed to retrieve list of SSH authentication methods: Failed getting response"

It hangs for about 30s-60s before giving the message above.

Remotes (I swapped from https to SSH):

origin  git@github.com:Huckler/Game.git (fetch)
origin  git@github.com:Huckler/Game.git (push)

SSH keys verified functional with VSCode as well as git client.

**Comment by ChronicallySerious** [comment]
@Huckler That looks like a separate problem. Could you create a new issue with the error message, Godot version, plugin version and the underlying OS?

**Comment by Huckler** [comment]
Yep! Will do.
